//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReferenceOrder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceOrder.IShopServiceBaseOf_Order")]
    public interface IShopServiceBaseOf_Order {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/Create", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/CreateResponse")]
        void Create(DomainModel.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/Create", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(DomainModel.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/GetItems", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/GetItemsResponse")]
        DomainModel.Order[] GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/GetItems", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/GetItemsResponse")]
        System.Threading.Tasks.Task<DomainModel.Order[]> GetItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/Update", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/UpdateResponse")]
        void Update(DomainModel.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/Update", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(DomainModel.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/Delete", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/DeleteResponse")]
        void Delete(DomainModel.Order item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_Order/Delete", ReplyAction="http://tempuri.org/IShopServiceBaseOf_Order/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(DomainModel.Order item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopServiceBaseOf_OrderChannel : Client.ServiceReferenceOrder.IShopServiceBaseOf_Order, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopServiceBaseOf_OrderClient : System.ServiceModel.ClientBase<Client.ServiceReferenceOrder.IShopServiceBaseOf_Order>, Client.ServiceReferenceOrder.IShopServiceBaseOf_Order {
        
        public ShopServiceBaseOf_OrderClient() {
        }
        
        public ShopServiceBaseOf_OrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopServiceBaseOf_OrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceBaseOf_OrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceBaseOf_OrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(DomainModel.Order item) {
            base.Channel.Create(item);
        }
        
        public System.Threading.Tasks.Task CreateAsync(DomainModel.Order item) {
            return base.Channel.CreateAsync(item);
        }
        
        public DomainModel.Order[] GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<DomainModel.Order[]> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
        
        public void Update(DomainModel.Order item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(DomainModel.Order item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public void Delete(DomainModel.Order item) {
            base.Channel.Delete(item);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(DomainModel.Order item) {
            return base.Channel.DeleteAsync(item);
        }
    }
}
