//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReferenceProductPrice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProductPrice.IShopServiceBaseOf_ProductPrice")]
    public interface IShopServiceBaseOf_ProductPrice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/Create", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/CreateResponse")]
        void Create(DomainModel.ProductPrice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/Create", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(DomainModel.ProductPrice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/GetItems", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/GetItemsResponse")]
        DomainModel.ProductPrice[] GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/GetItems", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/GetItemsResponse")]
        System.Threading.Tasks.Task<DomainModel.ProductPrice[]> GetItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/Update", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/UpdateResponse")]
        void Update(DomainModel.ProductPrice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/Update", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(DomainModel.ProductPrice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/Delete", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/DeleteResponse")]
        void Delete(DomainModel.ProductPrice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopServiceBaseOf_ProductPrice/Delete", ReplyAction="http://tempuri.org/IShopServiceBaseOf_ProductPrice/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(DomainModel.ProductPrice item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopServiceBaseOf_ProductPriceChannel : Client.ServiceReferenceProductPrice.IShopServiceBaseOf_ProductPrice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopServiceBaseOf_ProductPriceClient : System.ServiceModel.ClientBase<Client.ServiceReferenceProductPrice.IShopServiceBaseOf_ProductPrice>, Client.ServiceReferenceProductPrice.IShopServiceBaseOf_ProductPrice {
        
        public ShopServiceBaseOf_ProductPriceClient() {
        }
        
        public ShopServiceBaseOf_ProductPriceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopServiceBaseOf_ProductPriceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceBaseOf_ProductPriceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceBaseOf_ProductPriceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(DomainModel.ProductPrice item) {
            base.Channel.Create(item);
        }
        
        public System.Threading.Tasks.Task CreateAsync(DomainModel.ProductPrice item) {
            return base.Channel.CreateAsync(item);
        }
        
        public DomainModel.ProductPrice[] GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<DomainModel.ProductPrice[]> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
        
        public void Update(DomainModel.ProductPrice item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(DomainModel.ProductPrice item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public void Delete(DomainModel.ProductPrice item) {
            base.Channel.Delete(item);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(DomainModel.ProductPrice item) {
            return base.Channel.DeleteAsync(item);
        }
    }
}
